### ISSUE TITLE
Our Project information

### ISSUE THREAD

**Issue by iammouaz** [iammouaz/JavaScript-capstone#21]
Our Project :

https://github.com/iammouaz/JavaScript-capstone/projects/1

and we are two people working on this project 
its me and @marcosmerida

**Comment by henatan99** [comment]
Hi team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Required Changes ♻️
- [x] There should be a circle with the user's avatar on each card. Please see the example below and make changes accordingly. 
![image](https://user-images.githubusercontent.com/64894927/137811370-687ec8bc-376d-4722-a679-62da624d1083.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by carlos-ssh** [comment]
Hi @iammouaz , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![Approved](https://user-images.githubusercontent.com/22258274/137816969-ab17b9f7-df05-4b57-99aa-c4ea674f6809.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
